# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\AV_GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AV_App(object):
    def setupUi(self, AV_App):
        AV_App.setObjectName("AV_App")
        AV_App.resize(856, 675)
        AV_App.setMinimumSize(QtCore.QSize(856, 675))
        AV_App.setMaximumSize(QtCore.QSize(856, 675))
        font = QtGui.QFont()
        font.setPointSize(8)
        AV_App.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\AV_Icons/av-favicon-color.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        AV_App.setWindowIcon(icon)
        AV_App.setStyleSheet("*{\n"
"border: none;\n"
"background:none;\n"
"background-color: rgb(255, 255, 255);\n"
"padding: 0;\n"
"margin: 0;\n"
"}")
        AV_App.setIconSize(QtCore.QSize(48, 48))
        self.centralwidget = QtWidgets.QWidget(AV_App)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.upperMenu = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.upperMenu.sizePolicy().hasHeightForWidth())
        self.upperMenu.setSizePolicy(sizePolicy)
        self.upperMenu.setMinimumSize(QtCore.QSize(0, 0))
        self.upperMenu.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(97, 151, 132, 169), stop:0.221591 rgba(97, 151, 132, 255), stop:0.761364 rgba(97, 151, 132, 255), stop:1 rgba(97, 151, 132, 169));")
        self.upperMenu.setObjectName("upperMenu")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.upperMenu)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.SubUpperMenu = QtWidgets.QWidget(self.upperMenu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SubUpperMenu.sizePolicy().hasHeightForWidth())
        self.SubUpperMenu.setSizePolicy(sizePolicy)
        self.SubUpperMenu.setMinimumSize(QtCore.QSize(855, 0))
        self.SubUpperMenu.setMaximumSize(QtCore.QSize(855, 16777215))
        self.SubUpperMenu.setStyleSheet("background-color: transparent;\n"
"")
        self.SubUpperMenu.setObjectName("SubUpperMenu")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.SubUpperMenu)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.logoPlace = QtWidgets.QWidget(self.SubUpperMenu)
        self.logoPlace.setStyleSheet("background-color: transparent;\n"
"")
        self.logoPlace.setObjectName("logoPlace")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.logoPlace)
        self.horizontalLayout_2.setContentsMargins(9, -1, -1, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.logo = QtWidgets.QLabel(self.logoPlace)
        self.logo.setMinimumSize(QtCore.QSize(111, 51))
        self.logo.setMaximumSize(QtCore.QSize(111, 51))
        self.logo.setStyleSheet("background-color: transparent;\n"
"")
        self.logo.setLineWidth(0)
        self.logo.setText("")
        self.logo.setPixmap(QtGui.QPixmap(".\\logo.png"))
        self.logo.setScaledContents(True)
        self.logo.setObjectName("logo")
        self.horizontalLayout_2.addWidget(self.logo)
        spacerItem = QtWidgets.QSpacerItem(615, 15, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.infoBtn = QtWidgets.QPushButton(self.logoPlace)
        self.infoBtn.setMinimumSize(QtCore.QSize(28, 28))
        self.infoBtn.setMaximumSize(QtCore.QSize(28, 28))
        self.infoBtn.setStyleSheet("QPushButton{\n"
"    font: 12pt \"Alata\";\n"
"    color: rgb(0, 62, 41);\n"
"    padding: 2px 5px;\n"
"    margin: 0;\n"
"    background: none;\n"
"    background-color: transparent;\n"
"    border-radius: 14px;\n"
"    border-style: outset\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background:rgba(75, 117, 102, 90);    \n"
"    }")
        self.infoBtn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/AV ICO/AV_Icons/info.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.infoBtn.setIcon(icon1)
        self.infoBtn.setIconSize(QtCore.QSize(24, 24))
        self.infoBtn.setCheckable(True)
        self.infoBtn.setObjectName("infoBtn")
        self.horizontalLayout_2.addWidget(self.infoBtn)
        spacerItem1 = QtWidgets.QSpacerItem(5, 28, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.helpBtn = QtWidgets.QPushButton(self.logoPlace)
        self.helpBtn.setMinimumSize(QtCore.QSize(28, 28))
        self.helpBtn.setMaximumSize(QtCore.QSize(28, 28))
        self.helpBtn.setStyleSheet("QPushButton{\n"
"    font: 12pt \"Alata\";\n"
"    color: rgb(0, 62, 41);\n"
"    padding: 2px 5px;\n"
"    margin: 0;\n"
"    background: none;\n"
"    background-color: transparent;\n"
"    border-radius: 14px;\n"
"    border-style: outset\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background:rgba(75, 117, 102, 90);    \n"
"    }")
        self.helpBtn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/AV ICO/AV_Icons/help.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.helpBtn.setIcon(icon2)
        self.helpBtn.setIconSize(QtCore.QSize(24, 24))
        self.helpBtn.setCheckable(True)
        self.helpBtn.setObjectName("helpBtn")
        self.horizontalLayout_2.addWidget(self.helpBtn)
        spacerItem2 = QtWidgets.QSpacerItem(5, 28, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.exitBtn = QtWidgets.QPushButton(self.logoPlace)
        self.exitBtn.setMinimumSize(QtCore.QSize(28, 28))
        self.exitBtn.setMaximumSize(QtCore.QSize(28, 28))
        self.exitBtn.setStyleSheet("QPushButton{\n"
"    font: 12pt \"Alata\";\n"
"    color: rgb(0, 62, 41);\n"
"    padding: 2px 5px;\n"
"    margin: 0;\n"
"    background: none;\n"
"    background-color: transparent;\n"
"    border-radius: 14px;\n"
"    border-style: outset\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background:rgba(75, 117, 102, 90);    \n"
"    }")
        self.exitBtn.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/AV ICO/AV_Icons/power.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exitBtn.setIcon(icon3)
        self.exitBtn.setIconSize(QtCore.QSize(27, 27))
        self.exitBtn.setCheckable(True)
        self.exitBtn.setObjectName("exitBtn")
        self.horizontalLayout_2.addWidget(self.exitBtn)
        self.verticalLayout_3.addWidget(self.logoPlace, 0, QtCore.Qt.AlignTop)
        self.buttonsPlace = QtWidgets.QWidget(self.SubUpperMenu)
        self.buttonsPlace.setStyleSheet("")
        self.buttonsPlace.setObjectName("buttonsPlace")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.buttonsPlace)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.scansBtn = QtWidgets.QPushButton(self.buttonsPlace)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scansBtn.sizePolicy().hasHeightForWidth())
        self.scansBtn.setSizePolicy(sizePolicy)
        self.scansBtn.setMinimumSize(QtCore.QSize(100, 40))
        self.scansBtn.setToolTipDuration(-1)
        self.scansBtn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.scansBtn.setAutoFillBackground(False)
        self.scansBtn.setStyleSheet("QPushButton{\n"
"    font: 12pt \"Alata\";\n"
"    color: rgb(0, 62, 41);\n"
"    padding: 2px 5px;\n"
"    margin: 0;\n"
"    background-color: transparent;    \n"
"    border-top-left-radius: 10px;\n"
"    border-top-right-radius: 10px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background:rgba(75, 117, 102, 90);    \n"
"    }")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/AV ICO/AV_Icons/scan-virus.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.scansBtn.setIcon(icon4)
        self.scansBtn.setIconSize(QtCore.QSize(24, 24))
        self.scansBtn.setCheckable(True)
        self.scansBtn.setObjectName("scansBtn")
        self.horizontalLayout.addWidget(self.scansBtn)
        spacerItem3 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.theatsBtn = QtWidgets.QPushButton(self.buttonsPlace)
        self.theatsBtn.setMinimumSize(QtCore.QSize(100, 40))
        self.theatsBtn.setStyleSheet("QPushButton{\n"
"    font: 12pt \"Alata\";\n"
"    color: rgb(0, 62, 41);\n"
"    padding: 2px 5px;\n"
"    margin: 0;\n"
"    background-color: transparent;    \n"
"    border-top-left-radius: 10px;\n"
"    border-top-right-radius: 10px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background:rgba(75, 117, 102, 90);    \n"
"    }")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/AV ICO/AV_Icons/data.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.theatsBtn.setIcon(icon5)
        self.theatsBtn.setIconSize(QtCore.QSize(24, 24))
        self.theatsBtn.setCheckable(True)
        self.theatsBtn.setObjectName("theatsBtn")
        self.horizontalLayout.addWidget(self.theatsBtn)
        spacerItem4 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.settingsBtn = QtWidgets.QPushButton(self.buttonsPlace)
        self.settingsBtn.setMinimumSize(QtCore.QSize(109, 40))
        self.settingsBtn.setStyleSheet("QPushButton{\n"
"    font: 12pt \"Alata\";\n"
"    color: rgb(0, 62, 41);\n"
"    padding: 2px 5px;\n"
"    margin: 0;\n"
"    background-color: transparent;    \n"
"    border-top-left-radius: 10px;\n"
"    border-top-right-radius: 10px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background:rgba(75, 117, 102, 90);    \n"
"    }")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/AV ICO/AV_Icons/settings.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.settingsBtn.setIcon(icon6)
        self.settingsBtn.setIconSize(QtCore.QSize(24, 24))
        self.settingsBtn.setCheckable(True)
        self.settingsBtn.setFlat(False)
        self.settingsBtn.setObjectName("settingsBtn")
        self.horizontalLayout.addWidget(self.settingsBtn)
        self.verticalLayout_3.addWidget(self.buttonsPlace, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.verticalLayout_2.addWidget(self.SubUpperMenu, 0, QtCore.Qt.AlignTop)
        self.verticalLayout.addWidget(self.upperMenu)
        self.mainScreen = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainScreen.sizePolicy().hasHeightForWidth())
        self.mainScreen.setSizePolicy(sizePolicy)
        self.mainScreen.setMinimumSize(QtCore.QSize(855, 0))
        self.mainScreen.setMaximumSize(QtCore.QSize(855, 16777215))
        self.mainScreen.setStyleSheet("background:rgb(255, 255, 255)")
        self.mainScreen.setObjectName("mainScreen")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.mainScreen)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.stackedWidget = QtWidgets.QStackedWidget(self.mainScreen)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setMinimumSize(QtCore.QSize(856, 0))
        self.stackedWidget.setMaximumSize(QtCore.QSize(856, 16777215))
        self.stackedWidget.setLineWidth(0)
        self.stackedWidget.setObjectName("stackedWidget")
        self.threatsPage = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.threatsPage.sizePolicy().hasHeightForWidth())
        self.threatsPage.setSizePolicy(sizePolicy)
        self.threatsPage.setMinimumSize(QtCore.QSize(855, 0))
        self.threatsPage.setMaximumSize(QtCore.QSize(855, 16777215))
        self.threatsPage.setStyleSheet("background: none;\n"
"background-color: transparent;")
        self.threatsPage.setObjectName("threatsPage")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.threatsPage)
        self.gridLayout_3.setContentsMargins(0, 9, 0, 0)
        self.gridLayout_3.setHorizontalSpacing(0)
        self.gridLayout_3.setVerticalSpacing(9)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.resultsTitles = QtWidgets.QWidget(self.threatsPage)
        self.resultsTitles.setMinimumSize(QtCore.QSize(856, 53))
        self.resultsTitles.setMaximumSize(QtCore.QSize(856, 53))
        self.resultsTitles.setStyleSheet("background: none;\n"
"background-color: transparent;")
        self.resultsTitles.setObjectName("resultsTitles")
        self.titles = QtWidgets.QHBoxLayout(self.resultsTitles)
        self.titles.setContentsMargins(0, 0, 0, 0)
        self.titles.setSpacing(0)
        self.titles.setObjectName("titles")
        self.fileNameLabel = QtWidgets.QLabel(self.resultsTitles)
        self.fileNameLabel.setMinimumSize(QtCore.QSize(351, 51))
        self.fileNameLabel.setMaximumSize(QtCore.QSize(351, 51))
        self.fileNameLabel.setStyleSheet("font: 12pt \"Alata\";\n"
"padding: 2px 5px;\n"
"margin: 0;\n"
"color: rgb(0, 62, 41);\n"
"background: none;\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(97, 151, 132, 169), stop:1 rgba(97, 151, 132, 255));\n"
"border-top-left-radius: 10px;\n"
"border-top-right-radius: 10px;\n"
"border-bottom-right-radius: 10px;\n"
"border-bottom-left-radius: 10px")
        self.fileNameLabel.setObjectName("fileNameLabel")
        self.titles.addWidget(self.fileNameLabel)
        self.StatusLabel = QtWidgets.QLabel(self.resultsTitles)
        self.StatusLabel.setMinimumSize(QtCore.QSize(320, 0))
        self.StatusLabel.setMaximumSize(QtCore.QSize(320, 51))
        self.StatusLabel.setStyleSheet("font: 12pt \"Alata\";\n"
"padding: 2px 5px;\n"
"margin: 0;\n"
"color: rgb(0, 62, 41);\n"
"background: none;\n"
"background-color:rgb(97, 151, 132);\n"
"border-top-left-radius: 10px;\n"
"border-top-right-radius: 10px;\n"
"border-bottom-right-radius: 10px;\n"
"border-bottom-left-radius: 10px")
        self.StatusLabel.setObjectName("StatusLabel")
        self.titles.addWidget(self.StatusLabel)
        self.sizeLabel = QtWidgets.QLabel(self.resultsTitles)
        self.sizeLabel.setMinimumSize(QtCore.QSize(152, 51))
        self.sizeLabel.setMaximumSize(QtCore.QSize(152, 51))
        self.sizeLabel.setStyleSheet("font: 12pt \"Alata\";\n"
"padding: 2px 5px;\n"
"margin: 0;\n"
"color: rgb(0, 62, 41);\n"
"background: none;\n"
"background-color:qlineargradient(spread:pad, x1:1, y1:0, x2:0, y2:0, stop:0 rgba(97, 151, 132, 169), stop:1 rgba(97, 151, 132, 255));\n"
"border-top-left-radius: 10px;\n"
"border-top-right-radius: 10px;\n"
"border-bottom-right-radius: 10px;\n"
"border-bottom-left-radius: 10px")
        self.sizeLabel.setObjectName("sizeLabel")
        self.titles.addWidget(self.sizeLabel)
        self.gridLayout_3.addWidget(self.resultsTitles, 0, 0, 1, 1)
        self.scrollArea = QtWidgets.QScrollArea(self.threatsPage)
        self.scrollArea.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setMinimumSize(QtCore.QSize(856, 495))
        self.scrollArea.setMaximumSize(QtCore.QSize(856, 16777215))
        self.scrollArea.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.scrollArea.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.scrollArea.setStyleSheet("QScrollBar:vertical {\n"
"            border: 0px solid #999999;\n"
"            background:white;\n"
"            width:10px;    \n"
"            margin: 0px 0px 0px 0px;\n"
"        }\n"
"        QScrollBar::handle:vertical {         \n"
"       \n"
"            min-height: 0px;\n"
"              border: 0px solid red;\n"
"            border-radius: 4px;\n"
"            background-color:qlineargradient(spread:pad, x1:1, y1:0, x2:0, y2:0, stop:0 rgba(97, 151, 132, 169), stop:1 rgba(97, 151, 132, 255));\n"
"        }\n"
"        QScrollBar::add-line:vertical {       \n"
"            height: 0px;\n"
"            subcontrol-position: bottom;\n"
"            subcontrol-origin: margin;\n"
"        }\n"
"        QScrollBar::sub-line:vertical {\n"
"            height: 0 px;\n"
"            subcontrol-position: top;\n"
"            subcontrol-origin: margin;\n"
"        }\n"
"")
        self.scrollArea.setFrameShadow(QtWidgets.QFrame.Plain)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.scrollArea.setWidgetResizable(False)
        self.scrollArea.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.scrollArea.setObjectName("scrollArea")
        self.filesResults = QtWidgets.QWidget()
        self.filesResults.setGeometry(QtCore.QRect(0, 0, 856, 495))
        self.filesResults.setMaximumSize(QtCore.QSize(865, 16777215))
        self.filesResults.setStyleSheet("background: none;\n"
"background-color: transparent;")
        self.filesResults.setObjectName("filesResults")
        self.scrollArea.setWidget(self.filesResults)
        self.gridLayout_3.addWidget(self.scrollArea, 1, 0, 1, 1, QtCore.Qt.AlignTop)
        self.stackedWidget.addWidget(self.threatsPage)
        self.scansPage = QtWidgets.QWidget()
        self.scansPage.setObjectName("scansPage")
        self.gridLayout = QtWidgets.QGridLayout(self.scansPage)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem5 = QtWidgets.QSpacerItem(20, 68, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem5, 0, 1, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(184, 58, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem6, 1, 0, 1, 1)
        self.filePathWidget = QtWidgets.QWidget(self.scansPage)
        self.filePathWidget.setMinimumSize(QtCore.QSize(521, 63))
        self.filePathWidget.setMaximumSize(QtCore.QSize(521, 4000))
        self.filePathWidget.setObjectName("filePathWidget")
        self.filePathLayout = QtWidgets.QHBoxLayout(self.filePathWidget)
        self.filePathLayout.setContentsMargins(0, 0, 0, 0)
        self.filePathLayout.setSpacing(0)
        self.filePathLayout.setObjectName("filePathLayout")
        self.filePath = QtWidgets.QLabel(self.filePathWidget)
        self.filePath.setMinimumSize(QtCore.QSize(400, 51))
        self.filePath.setMaximumSize(QtCore.QSize(400, 51))
        self.filePath.setStyleSheet("font: 12pt \"Alata\";\n"
"padding: 2px 5px;\n"
"margin: 0;\n"
"background: none;\n"
"background-color: rgb(208, 222, 216);\n"
"border-top-left-radius: 10px;\n"
"border-bottom-left-radius: 10px")
        self.filePath.setObjectName("filePath")
        self.filePathLayout.addWidget(self.filePath)
        self.filePathBtn = QtWidgets.QPushButton(self.filePathWidget)
        self.filePathBtn.setMinimumSize(QtCore.QSize(51, 51))
        self.filePathBtn.setMaximumSize(QtCore.QSize(51, 51))
        self.filePathBtn.setStyleSheet("QPushButton{\n"
"    font: 12pt \"Alata\";\n"
"    color: rgb(0, 62, 41);\n"
"    padding: 2px 5px;\n"
"    margin: 0;\n"
"    background: none;\n"
"    background-color: rgb(97, 151, 132);\n"
"    border-style: outset\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"background:rgba(75, 117, 102, 220)\n"
"    }")
        self.filePathBtn.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/AV ICO/AV_Icons/onefile.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.filePathBtn.setIcon(icon7)
        self.filePathBtn.setIconSize(QtCore.QSize(24, 24))
        self.filePathBtn.setCheckable(True)
        self.filePathBtn.setObjectName("filePathBtn")
        self.filePathLayout.addWidget(self.filePathBtn)
        self.folderPathBtn = QtWidgets.QPushButton(self.filePathWidget)
        self.folderPathBtn.setMinimumSize(QtCore.QSize(51, 51))
        self.folderPathBtn.setMaximumSize(QtCore.QSize(51, 51))
        self.folderPathBtn.setStyleSheet("QPushButton{\n"
"    font: 12pt \"Alata\";\n"
"    color: rgb(0, 62, 41);\n"
"    padding: 2px 5px;\n"
"    margin: 0;\n"
"    background: none;\n"
"    background-color: rgb(97, 151, 132);\n"
"    border-top-right-radius: 10px;\n"
"    border-bottom-right-radius: 10px;\n"
"    border-style: outset\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"background:rgba(75, 117, 102, 220)\n"
"    }")
        self.folderPathBtn.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/AV ICO/AV_Icons/files.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.folderPathBtn.setIcon(icon8)
        self.folderPathBtn.setIconSize(QtCore.QSize(24, 24))
        self.folderPathBtn.setCheckable(True)
        self.folderPathBtn.setObjectName("folderPathBtn")
        self.filePathLayout.addWidget(self.folderPathBtn)
        self.gridLayout.addWidget(self.filePathWidget, 1, 1, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(184, 48, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem7, 1, 2, 1, 1)
        self.ScanLayout = QtWidgets.QHBoxLayout()
        self.ScanLayout.setObjectName("ScanLayout")
        spacerItem8 = QtWidgets.QSpacerItem(145, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.ScanLayout.addItem(spacerItem8)
        self.scanBtn = QtWidgets.QPushButton(self.scansPage)
        self.scanBtn.setMinimumSize(QtCore.QSize(109, 40))
        self.scanBtn.setMaximumSize(QtCore.QSize(109, 40))
        font = QtGui.QFont()
        font.setFamily("Alata")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.scanBtn.setFont(font)
        self.scanBtn.setStyleSheet("QPushButton{\n"
"    font: 16pt \"Alata\";\n"
"    color: rgb(0, 62, 41);\n"
"    padding: 2px 5px;\n"
"    margin: 0;\n"
"    background: none;\n"
"    text-align: center middle;\n"
"    background-color: rgb(97, 151, 132);\n"
"    border-top-left-radius: 10px;\n"
"    border-bottom-left-radius: 10px;\n"
"    border-top-right-radius: 10px;\n"
"    border-bottom-right-radius: 10px;\n"
"}\n"
"QPushButton:hover {\n"
"background:rgba(75, 117, 102, 220)\n"
"    }\n"
"")
        self.scanBtn.setIconSize(QtCore.QSize(0, 0))
        self.scanBtn.setCheckable(True)
        self.scanBtn.setFlat(False)
        self.scanBtn.setObjectName("scanBtn")
        self.ScanLayout.addWidget(self.scanBtn)
        spacerItem9 = QtWidgets.QSpacerItem(226, 58, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.ScanLayout.addItem(spacerItem9)
        self.gridLayout.addLayout(self.ScanLayout, 2, 0, 1, 3)
        spacerItem10 = QtWidgets.QSpacerItem(20, 168, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem10, 3, 1, 1, 1)
        self.scanInfo = QtWidgets.QWidget(self.scansPage)
        self.scanInfo.setMinimumSize(QtCore.QSize(856, 201))
        self.scanInfo.setMaximumSize(QtCore.QSize(856, 201))
        self.scanInfo.setCursor(QtGui.QCursor(QtCore.Qt.SizeAllCursor))
        self.scanInfo.setObjectName("scanInfo")
        self.scanTitle = QtWidgets.QLabel(self.scanInfo)
        self.scanTitle.setGeometry(QtCore.QRect(11, 5, 835, 61))
        self.scanTitle.setMinimumSize(QtCore.QSize(0, 0))
        self.scanTitle.setMaximumSize(QtCore.QSize(1000000, 1000000))
        self.scanTitle.setStyleSheet("font: 16pt \"Alata\";\n"
"color: rgb(0, 62, 41);\n"
"padding: 2px 5px;\n"
"margin: 0;\n"
"background: none;\n"
"text-align: center middle;\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(97, 151, 132, 169), stop:0.221591 rgba(97, 151, 132, 255), stop:0.761364 rgba(97, 151, 132, 255), stop:1 rgba(97, 151, 132, 169));\n"
"border-top-left-radius: 10px;\n"
"border-top-right-radius: 10px;\n"
"border-bottom-right-radius: 10px;\n"
"border-bottom-left-radius: 10px")
        self.scanTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.scanTitle.setObjectName("scanTitle")
        self.scanTime = QtWidgets.QLabel(self.scanInfo)
        self.scanTime.setGeometry(QtCore.QRect(10, 75, 835, 51))
        self.scanTime.setStyleSheet("font: 12pt \"Alata\";\n"
"padding: 2px 5px;\n"
"margin: 0;\n"
"background: none;\n"
"border-top-left-radius: 10px;\n"
"border-top-right-radius: 10px;\n"
"background-color: rgb(208, 222, 216);\n"
"border-bottom-right-radius: 10px;\n"
"border-bottom-left-radius: 10px")
        self.scanTime.setObjectName("scanTime")
        self.numThreats = QtWidgets.QLabel(self.scanInfo)
        self.numThreats.setGeometry(QtCore.QRect(10, 135, 413, 51))
        self.numThreats.setStyleSheet("font: 12pt \"Alata\";\n"
"padding: 2px 5px;\n"
"margin: 0;\n"
"background: none;\n"
"background-color: rgb(208, 222, 216);\n"
"border-top-left-radius: 10px;\n"
"border-top-right-radius: 10px;\n"
"border-bottom-right-radius: 10px;\n"
"border-bottom-left-radius: 10px")
        self.numThreats.setObjectName("numThreats")
        self.numScanned = QtWidgets.QLabel(self.scanInfo)
        self.numScanned.setGeometry(QtCore.QRect(432, 135, 413, 51))
        self.numScanned.setStyleSheet("font: 12pt \"Alata\";\n"
"padding: 2px 5px;\n"
"margin: 0;\n"
"background: none;\n"
"background-color: rgb(208, 222, 216);\n"
"border-top-left-radius: 10px;\n"
"border-top-right-radius: 10px;\n"
"border-bottom-right-radius: 10px;\n"
"border-bottom-left-radius: 10px")
        self.numScanned.setObjectName("numScanned")
        self.gridLayout.addWidget(self.scanInfo, 4, 0, 1, 3)
        self.filePathWidget.raise_()
        self.scanInfo.raise_()
        self.stackedWidget.addWidget(self.scansPage)
        self.settingsPage = QtWidgets.QWidget()
        self.settingsPage.setObjectName("settingsPage")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.settingsPage)
        self.gridLayout_4.setContentsMargins(9, 9, 9, 9)
        self.gridLayout_4.setSpacing(9)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.widget_3 = QtWidgets.QWidget(self.settingsPage)
        self.widget_3.setStyleSheet("font: 12pt \"Alata\";\n"
"padding: 2px 5px;\n"
"margin: 0;\n"
"color: rgb(0, 62, 41);\n"
"background: none;\n"
"background-color:rgb(208, 222, 216);\n"
"border-top-left-radius: 10px;\n"
"border-top-right-radius: 10px;\n"
"border-bottom-right-radius: 10px;\n"
"border-bottom-left-radius: 10px")
        self.widget_3.setObjectName("widget_3")
        self.gridLayout_4.addWidget(self.widget_3, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.settingsPage)
        self.helpPage = QtWidgets.QWidget()
        self.helpPage.setObjectName("helpPage")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.helpPage)
        self.gridLayout_5.setContentsMargins(9, 9, 9, 9)
        self.gridLayout_5.setSpacing(9)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.widget_2 = QtWidgets.QWidget(self.helpPage)
        self.widget_2.setStyleSheet("padding: 2px 5px;\n"
"margin: 0;\n"
"background: none;\n"
"background-color:rgb(208, 222, 216);\n"
"border-top-left-radius: 10px;\n"
"border-top-right-radius: 10px;\n"
"border-bottom-right-radius: 10px;\n"
"border-bottom-left-radius: 10px")
        self.widget_2.setObjectName("widget_2")
        self.label_6 = QtWidgets.QLabel(self.widget_2)
        self.label_6.setGeometry(QtCore.QRect(0, 0, 819, 51))
        font = QtGui.QFont()
        font.setFamily("Alata")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.label_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_6.setStyleSheet("background-color: transparent;    \n"
"")
        self.label_6.setScaledContents(True)
        self.label_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.widget_2)
        self.label_7.setGeometry(QtCore.QRect(0, 50, 819, 191))
        font = QtGui.QFont()
        font.setFamily("Alata")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.label_7.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_7.setStyleSheet("background-color: transparent;    \n"
"")
        self.label_7.setTextFormat(QtCore.Qt.AutoText)
        self.label_7.setScaledContents(True)
        self.label_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_7.setWordWrap(False)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.widget_2)
        self.label_8.setGeometry(QtCore.QRect(0, 250, 819, 51))
        font = QtGui.QFont()
        font.setFamily("Alata")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.label_8.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_8.setStyleSheet("background-color: transparent;    \n"
"")
        self.label_8.setScaledContents(True)
        self.label_8.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.widget_2)
        self.label_9.setGeometry(QtCore.QRect(0, 300, 819, 141))
        font = QtGui.QFont()
        font.setFamily("Alata")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_9.setFont(font)
        self.label_9.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.label_9.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_9.setStyleSheet("background-color: transparent;    \n"
"")
        self.label_9.setScaledContents(True)
        self.label_9.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_5.addWidget(self.widget_2, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.helpPage)
        self.infoPage = QtWidgets.QWidget()
        self.infoPage.setStyleSheet("")
        self.infoPage.setObjectName("infoPage")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.infoPage)
        self.gridLayout_6.setContentsMargins(9, 9, 9, 9)
        self.gridLayout_6.setSpacing(9)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.widget = QtWidgets.QWidget(self.infoPage)
        self.widget.setMinimumSize(QtCore.QSize(837, 548))
        self.widget.setMaximumSize(QtCore.QSize(837, 548))
        self.widget.setStyleSheet("padding: 2px 5px;\n"
"margin: 0;\n"
"color: rgb(0, 0, 0);\n"
"background: none;\n"
"background-color:rgb(208, 222, 216);\n"
"border-top-left-radius: 10px;\n"
"border-top-right-radius: 10px;\n"
"border-bottom-right-radius: 10px;\n"
"border-bottom-left-radius: 10px")
        self.widget.setObjectName("widget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem11 = QtWidgets.QSpacerItem(278, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem11)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setMinimumSize(QtCore.QSize(281, 125))
        self.label_2.setMaximumSize(QtCore.QSize(281, 125))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(".\\AV_Icons/logo-no-background.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        spacerItem12 = QtWidgets.QSpacerItem(278, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem12)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Alata")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setStyleSheet("background-color: transparent;    \n"
"")
        self.label.setScaledContents(True)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_5.addWidget(self.label)
        spacerItem13 = QtWidgets.QSpacerItem(20, 32, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem13)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setMinimumSize(QtCore.QSize(81, 71))
        self.label_4.setMaximumSize(QtCore.QSize(81, 71))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap(":/AV ICO/AV_Icons/file_type_python_icon_130221.ico"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setMinimumSize(QtCore.QSize(71, 71))
        self.label_3.setMaximumSize(QtCore.QSize(71, 71))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(":/AV ICO/AV_Icons/c_icon_132529.ico"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        spacerItem14 = QtWidgets.QSpacerItem(483, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem14)
        self.label_5 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Alata")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.gridLayout_6.addWidget(self.widget, 0, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.stackedWidget.addWidget(self.infoPage)
        self.verticalLayout_4.addWidget(self.stackedWidget)
        self.verticalLayout.addWidget(self.mainScreen)
        AV_App.setCentralWidget(self.centralwidget)

        self.retranslateUi(AV_App)
        self.stackedWidget.setCurrentIndex(1)
        self.exitBtn.clicked.connect(AV_App.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(AV_App)

    def retranslateUi(self, AV_App):
        _translate = QtCore.QCoreApplication.translate
        AV_App.setWindowTitle(_translate("AV_App", "AV by OG"))
        self.infoBtn.setToolTip(_translate("AV_App", "Info"))
        self.helpBtn.setToolTip(_translate("AV_App", "Help"))
        self.exitBtn.setToolTip(_translate("AV_App", "Close Application"))
        self.scansBtn.setToolTip(_translate("AV_App", "Scans"))
        self.scansBtn.setText(_translate("AV_App", "Scans"))
        self.theatsBtn.setToolTip(_translate("AV_App", "Results"))
        self.theatsBtn.setText(_translate("AV_App", "Threats"))
        self.settingsBtn.setToolTip(_translate("AV_App", "Settings"))
        self.settingsBtn.setText(_translate("AV_App", "Settings"))
        self.fileNameLabel.setText(_translate("AV_App", "File Name"))
        self.StatusLabel.setText(_translate("AV_App", "Status"))
        self.sizeLabel.setText(_translate("AV_App", "Actions"))
        self.filePath.setText(_translate("AV_App", "File / Folder Path..."))
        self.folderPathBtn.setToolTip(_translate("AV_App", "Choose Path..."))
        self.scanBtn.setToolTip(_translate("AV_App", "Start Scan"))
        self.scanBtn.setText(_translate("AV_App", "Scan"))
        self.scanTitle.setText(_translate("AV_App", "Scan Result"))
        self.scanTime.setText(_translate("AV_App", "Last Scan Time: "))
        self.numThreats.setText(_translate("AV_App", "0 Threats Found"))
        self.numScanned.setText(_translate("AV_App", "0 Files Scanned"))
        self.label_6.setText(_translate("AV_App", "To Start A Scan"))
        self.label_7.setText(_translate("AV_App", "1. Press the scans button in the upper tab\n"
"\n"
"2. Choose the file / folder to scan by pressing the file button\n"
"\n"
"3. Press the scan button to start scan\n"
"\n"
"4. The result will be shown in the button of the window and the threats in the threats page"))
        self.label_8.setText(_translate("AV_App", "How To Handle Threats"))
        self.label_9.setText(_translate("AV_App", "1. To see all the possible threats press the threats button\n"
"\n"
"2. For each file you can see is path and status (in default the file get transfered to a quarantine folder)\n"
"\n"
"3. You can choose if you want to delete the file or allow it (you can\'t change your decision later)"))
        self.label.setText(_translate("AV_App", "\n"
"Is An Anti-Virus That Use 2 Types Of Detections\n"
"Virus Signature Detection\n"
"&\n"
"Windows Malware Detection\n"
"It Is Program In Two Languages\n"
"Python & C++\n"
""))
        self.label_5.setText(_translate("AV_App", "By Ohad Gips 2024"))
import AV_Icons_rc
